#!/usr/bin/php -q
<?php

include_once("/usr/local/sbin/xen_common");
include_once("/usr/local/sbin/common_lib");
include_once("/usr/local/sbin/insta_common");
include_once("/usr/local/sbin/shared_lib");

if(count($argv) < 2){
	usage();
}

$mode="";

if($argv[1] == "pre") {
	$mode ="pre";
}else if($argv[1] =="post"){
	$mode ="post";
}else{
	usage();
}

function usage(){
        die("Please choose: pre or post\n");
}

# Pre is run before startEngine but AFTER ADS is mounted (we use nimbusdb alot)
if($mode == "pre"){
	$id = setInstallID();
	echo "Alike InstallID: $id\n";

	$hostIP = getSetting("hostIP");
	if(empty($hostIP)){
		$hostIP = trim(shell_exec("hostname -I"));
		setSetting("hostIP", $hostIP);
	}
	// set smb passwords
	updateLocalUsers();
	$cnf = makeMungeConf();
	echo "Backup Data transfer port bound to: $cnf\n";

	// is this necessary now?
	echo "Syncing new DB settings to ADS\n";
	exec("/usr/local/sbin/dbSyncer /home/alike/Alike/DBs/nimbusdb.db");	

	return; // The below is only needed for instaBoot features, currently not available

	echo "Checking A3 SR Setup\n";
	echo makeInstaConfigs();

	echo "Enabling Xen-specific safety measures for A3 \n";
	applyXenSafety();

	echo "Checking for stray/orphan Alike_SRs\n";	
	$hids = getPoolMasters();
        foreach($hids as $hid){
		xen_connect($hid);
		checkOrphanSrs();
	}

}

if($mode == "post"){
	echo "Plugging NFS SR into Xen Pool(s)\n";
	replugAll();

	echo "Checking and preparing ABD templates\n";
	setupABDs();

	echo "Resuming any paused ABDs\n";
	findAndUnpauseABDs();
}


function setupABDs(){
	$hids = getPoolMasters();
        foreach($hids as $hid){
		$h = getHost($hid);
		$cmd = "/usr/local/sbin/abdAdmin import $h->hostID";
		echo shell_exec($cmd);
	}
}
function findAndUnpauseABDs(){
        $sql = "SELECT uuid,poolID from Appliance order by poolID";
	$out = dbGet("nimbus", $sql);
        $curHost = null;
	foreach($out as $a){
                if($curHost == null || $curHost->poolID != $a->poolID){
                        $curHost = getPoolMasters($a->poolID);
                        $h = $curHost[0];
                        xen_connect($h);
                }
                $cmd = "vm-unpause uuid=$a->uuid";
                $rez = trim(xen_call($cmd));
        }
}


function replugAll(){
        $all = getHosts();
        foreach($all as $h){
                if($h->type == 2){
                        $cmd = "/usr/local/sbin/instaAdmin plugSrToHost $h->hostID";
                        echo shell_exec($cmd);
			scanSr($h->hostID);

                }
        }
}




function applyXenSafety(){
	$guid = trim(file_get_contents("/sys/hypervisor/uuid"));
	if(empty($guid)){
		echo "Couldn't find Xen Guid!\n";
		return;
	}

	$poolID = connectXapiByVm($guid);
	if(empty($poolID)){
		syslog(LOG_WARNING, "Could not find pool for A3 host- Failed to set A3 Xen safety restrictions!");
		return;
	}
	// prevent users from caussing serious harm by blocking 
	$cmd = "vm-param-set uuid=$guid blocked-operations:snapshot=false;";
	xen_call($cmd);
	$cmd = "vm-param-set uuid=$guid blocked-operations:checkpoint=false;";
	xen_call($cmd);
	$cmd = "vm-param-set uuid=$guid blocked-operations:suspend=false;";
	xen_call($cmd);
	$cmd = "vm-param-set uuid=$guid blocked-operations:migrate_send=false;";
	xen_call($cmd);
	$cmd = "vm-param-set uuid=$guid blocked-operations:pool_migrate=false;";
	xen_call($cmd);
}

?>
