#!/usr/bin/php -q
<?php

if(count($argv) < 2){
	usage();
}

if( trim(exec("whoami")) !="root"){ 
        die("Please run this script as root.\n");
}


updateToTag($argv[1]);

function usage(){
        die("Usage:\n\ta3_update [tag_num]\n\n");
}


function updateToTag($tag){
	exec("cd /root/a3");
	exec("git fetch --tags");
	exec("git rev-parse --verify refs/tags/$tag", $out, $code);
	if($code !== 0){
		die("Tag ($tag) not found!\n");
	}
	exec("git checkout tags/$tag", $out, $code);
	if($code !== 0){
		echo "Failed to checkout $tag\n";
		foreach($out as $l){
			echo "$l\n";
		}
		exit(1);
	}

	updateAssets($tag);
}

function updateAssets($tag){
	$base = "/root/a3";
	if(file_exists("$base/appliance/alike_crontab")){
		exec("crontab -u alike $base/appliance/alike_crontab");
		unlink("$base/appliance/alike_crontab");
	}
	exec("cp -f $base/hooks/* /home/alike/Alike/hooks/");
	exec("mv -f $base/binaries/BackupScheduler.exe /home/alike/Alike/");
	exec("cp -f $base/appliance/* /usr/local/sbin/");
	exec("cp -f $base/binaries/*.dll /usr/local/sbin/");
	exec("cp -f $base/binaries/*.exe /usr/local/sbin/");
	exec("cp -f $base/binaries/blkfs /usr/local/sbin/");
	exec("cp -f $base/binaries/abd.dat.7z /home/alike/Alike/ext/");
	exec("cp -r $base/binaries/java/* /home/alike/Alike/java/");

	exec("chown -R alike:alike /home/alike");
	exec("chmod 755 /usr/local/sbin/*");
	exec("chmod 755 /home/alike/Alike/hooks/*");


	file_put_contents("/home/alike/Alike/build.num", $tag);

}

?>
