#!/usr/bin/php -q
<?php

if(count($argv) < 2){
	usage();
}

if( trim(exec("whoami")) !="root"){ 
        die("Please run this script as root.\n");
}


updateToTag($argv[1]);

function usage(){
        die("Usage:\n\ta3_update [tag_num]\n\n");
}


function updateToTag($tag){
	exec("git -C /root/a3 fetch --tags");
	exec("git -C /root/a3 rev-parse --verify refs/tags/$tag", $out, $code);
	if($code !== 0){
		die("Build (Tag) [$tag] not found!\n");
	}
	exec("git -C /root/a3 checkout tags/$tag", $out, $code);
	if($code !== 0){
		echo "Failed to checkout $tag\n";
		foreach($out as $l){
			echo "$l\n";
		}
		exit(1);
	}

	updateAssets($tag);
	echo "Update to #$tag complete.\nA restart is required for all updates to take effect\nReboot now? (y/n): ";	
	$resp = trim(fgets(STDIN));
	if (strcasecmp($resp, "y") == 0) { $resp = true; }
	else{ $resp = false; }

	if($resp){
		exec("sudo reboot");
		exit(0);
	}
	echo "Reboot skipped.  Please restart as soon as you are able.\n";
	
}

function updateAssets($tag){
	$base = "/root/a3";
	if(file_exists("$base/appliance/alike_crontab")){
		exec("crontab -u alike $base/appliance/alike_crontab");
		unlink("$base/appliance/alike_crontab");
	}
	exec("cp -f $base/configs/rsyslog.conf /etc/ 2>/dev/null");
	exec("cp -f $base/hooks/* /home/alike/Alike/hooks/ 2>/dev/null");
	exec("mv -f $base/binaries/BackupScheduler.exe /home/alike/Alike/ 2>/dev/null");
	exec("cp -f $base/appliance/* /usr/local/sbin/");
	exec("cp -f $base/binaries/*.dll /usr/local/sbin/");
	exec("cp -f $base/binaries/*.exe /usr/local/sbin/");
	exec("cp -f $base/binaries/blkfs /usr/local/sbin/");
	exec("cp -f $base/binaries/abd.dat.7z /home/alike/Alike/ext/");
	exec("cp -r $base/binaries/java/* /home/alike/Alike/java/");

	exec("chown -R alike:alike /home/alike");
	exec("chmod 755 /usr/local/sbin/*");
	exec("chmod 755 /home/alike/Alike/hooks/* 2>/dev/null");

	if (!file_exists("/usr/local/sbin/goofys")){
		exec("sudo wget https://github.com/kahing/goofys/releases/download/v0.24.0/goofys -O /usr/local/sbin/goofys");
		exec("sudo chmod 755 /usr/local/sbin/goofys");
	}


	file_put_contents("/home/alike/Alike/build.num", $tag);

}

?>
