#!/usr/bin/php -q
<?php
include_once("/usr/local/sbin/common_lib");

updateSystem();

function updateSystem(){
	$enable = getSetting("smtpNotify");
	if($enable != "on" && $enable != "1"){ 
		echo "SMTP is disabled.\n";
		return;
	}

	$o = new stdClass();
	$o->to = getSetting("smtpToAddress");
	$o->user = getSetting("smtpUsername");
	$o->from = $o->user;
	$o->pass = getSetting("smtpPassword");
	$o->server = getSetting("smtpServer");
	$o->port = getSetting("smtpPort");
	$o->useAuth = getSetting("useSMTPAuth");
	$o->useSSL = getSetting("useSMTPSSL");

	updateMSMTP($o);
}

function updateMSMTP($o){
	$str = "defaults\n";
	$str .= "add_missing_date_header on\n";
	$str .= "logfile		/home/alike/logs/mail.log\n";
	$str .= "tls_trust_file 	/etc/ssl/certs/ca-certificates.crt\n";
	$str .= "tls_certcheck off\n\n";
	$str .= "auth		on\n";

	if($o->useSSL == "1" || $o->useSSL == "on"){ 
		$str .= "tls		on\n";
	}
	$str .= "account		alike\n";
	$str .= "host		$o->server\n";
	$str .= "port		$o->port\n";
	$str .= "from		$o->from\n";
	$str .= "user		$o->user\n";
	$str .= "password	$o->pass\n";
	$str .= "\naccount default : 	alike\n";
	file_put_contents("/home/alike/.msmtprc",$str);
	exec("chmod 600 /home/alike/.msmtprc");
}

function updateMailRC($email){
	exec("echo 'alias alike ".$email."' > /home/alike/.mailrc");
}


?>
